# Generated by Django 3.1.2 on 2021-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='oferta',
            field=models.IntegerField(null=True),
        ),
    ]
