# Generated by Django 3.1.2 on 2021-02-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_auto_20210204_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_oferta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_producto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
