# Generated by Django 3.1.2 on 2021-02-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20210204_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.tienda'),
        ),
    ]
